<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>plus.ruoyi</groupId>
        <artifactId>ruoyi-common-pay</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-common-pay-balance</artifactId>

    <description>
        ruoyi-common-pay-balance 余额支付模块
    </description>

    <dependencies>
        <!-- 支付核心模块 -->
        <dependency>
            <groupId>plus.ruoyi</groupId>
            <artifactId>ruoyi-common-pay-core</artifactId>
        </dependency>
    </dependencies>

</project>
