<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>plus.ruoyi</groupId>
        <artifactId>ruoyi-common</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-common-serialmap</artifactId>

    <description>
        序列化映射模块 - 提供数据字典与多语言翻译功能
    </description>

    <dependencies>
        <!-- ================ 内部模块依赖 ================ -->
        <!-- JSON模块 - 提供序列化支持 -->
        <dependency>
            <groupId>plus.ruoyi</groupId>
            <artifactId>ruoyi-common-json</artifactId>
        </dependency>

        <!-- Redis模块 - 提供缓存支持 -->
        <dependency>
            <groupId>plus.ruoyi</groupId>
            <artifactId>ruoyi-common-redis</artifactId>
        </dependency>

        <!-- MyBatis模块 - 提供数据库访问能力 -->
        <dependency>
            <groupId>plus.ruoyi</groupId>
            <artifactId>ruoyi-common-mybatis</artifactId>
        </dependency>

        <!--   oss服务     -->
        <dependency>
            <groupId>plus.ruoyi</groupId>
            <artifactId>ruoyi-common-oss</artifactId>
        </dependency>
    </dependencies>
</project>
